/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentes;

import dominio.Comentario;
import dominio.Publicacion;
import java.awt.BorderLayout;

/**
 *
 * @author Equipo 6
 */
public class PanelPublicaciones extends javax.swing.JPanel {

    /**
     * Creates new form panelPublicaciones
     */
    public PanelPublicaciones() {
        initComponents();
    }
    
    public PanelPublicaciones(Publicacion publicacion){
        initComponents();
        int x=0,y=0;
        campoTextoPublicacion.setText(publicacion.getContenidoTex());
        labelFecha.setText(publicacion.getFechaHora().toString());
        labelUsuario.setText(publicacion.getUsuario().getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFecha = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoTextoPublicacion = new javax.swing.JTextArea();
        campoTextoComentar = new javax.swing.JTextField();
        botonComentar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(730, 202));

        labelFecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelFecha.setText("FECHA");

        labelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario.setText("USUARIO");

        campoTextoPublicacion.setColumns(20);
        campoTextoPublicacion.setRows(5);
        jScrollPane1.setViewportView(campoTextoPublicacion);

        campoTextoComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoComentarActionPerformed(evt);
            }
        });

        botonComentar.setText("Comentar");
        botonComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoTextoComentar, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonComentar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelFecha)
                        .addGap(162, 162, 162))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFecha)
                    .addComponent(labelUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoComentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonComentar))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComentarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonComentarActionPerformed

    private void campoTextoComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoComentarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoComentarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComentar;
    private javax.swing.JTextField campoTextoComentar;
    private javax.swing.JTextArea campoTextoPublicacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
